apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      # Use the container_name label for the log stream selector.
      derivedFields:
        - datasourceUid: loki
          matcherRegex: '"container_name":"([^"]+)"'
          name: container_name
          url: '$${__value.raw}'
