package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/collectors"
)

const namespace = "iot_simulator"

// Metrics holds all Prometheus collectors for the application.
type Metrics struct {
	ActiveSensors        prometheus.Gauge
	MessagesSent         *prometheus.CounterVec
	GeneratedValues      *prometheus.HistogramVec
	SensorRestarts       *prometheus.CounterVec
	MessagesReceived     prometheus.Counter
	NATSPublishSuccess   *prometheus.CounterVec
	NATSPublishFailures  *prometheus.CounterVec
	NATSPublishLatency   *prometheus.HistogramVec
	NATSConnectionStatus prometheus.Gauge
}

func NewMetrics(reg prometheus.Registerer) *Metrics {
	m := &Metrics{
		ActiveSensors: prometheus.NewGauge(prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "active_sensors",
			Help:      "The current number of active sensor goroutines.",
		}),
		MessagesSent: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: "sensor",
			Name:      "messages_sent_total",
			Help:      "Total number of messages sent by each sensor.",
		}, []string{"sensor_id"}),
		GeneratedValues: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: "sensor",
			Name:      "generated_values",
			Help:      "Distribution of values generated by sensors.",
			Buckets:   prometheus.LinearBuckets(0, 0.1, 10),
		}, []string{"sensor_id"}),
		SensorRestarts: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: "sensor",
			Name:      "restarts_total",
			Help:      "Total number of times a sensor has been restarted after a panic.",
		}, []string{"sensor_id"}),
		MessagesReceived: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: "aggregator",
			Name:      "messages_received_total",
			Help:      "Total number of messages received by the aggregator.",
		}),
		NATSPublishSuccess: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: "nats",
			Name:      "public_success_total",
			Help:      "Total number of successfully published messages to NATS.",
		}, []string{"sensor_id", "error_type"}),
		NATSPublishFailures: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: "nats",
			Name:      "publish_failures_total",
			Help:      "Total number of failed message publishes to NATS.",
		}, []string{"sensor_id", "error_type"}),
		NATSPublishLatency: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: "nats",
			Name:      "publish_latency_seconds",
			Help:      "Latency of publishing messages to NATS in seconds.",
			Buckets:   prometheus.ExponentialBuckets(0.001, 2, 10), // 1ms to ~1s
		}, []string{"sensor_id"}),
		NATSConnectionStatus: prometheus.NewGauge(prometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: "nats",
			Name:      "connection_status",
			Help:      "Nats connection status (1 = connected, 0 = disconnected).",
		}),
	}

	// Register all collectors with the provided registerer.
	reg.MustRegister(
		// Custom application metrics
		m.ActiveSensors,
		m.MessagesSent,
		m.GeneratedValues,
		m.SensorRestarts,
		m.MessagesReceived,
		m.NATSPublishSuccess,
		m.NATSPublishFailures,
		m.NATSPublishLatency,
		m.NATSConnectionStatus,

		// Go runtime and process metrics
		collectors.NewGoCollector(),
		collectors.NewProcessCollector(collectors.ProcessCollectorOpts{}),
	)

	return m
}
